# Generated by Django 5.2.6 on 2025-12-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_auth', '0002_alter_customer_profile_img_url'),
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['status'], name='suggestions_status_dc6c14_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['created_at'], name='suggestions_created_c428a6_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['category'], name='suggestions_categor_c7ad57_idx'),
        ),
    ]
