# Generated by Django 5.2.6 on 2025-10-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
